### ISSUE TITLE
(Optionally) assume guards to be false during exhaustiveness checking

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#100]
[Richard Bradley asked](https://groups.google.com/d/msg/scala-internals/KQtsxXHDe5Y/3AEqObFlAQAJ) to reopen https://issues.scala-lang.org/browse/SI-5365 on exhaustiveness checking. The bug is closed because of a judgement call, and I imagine people here have different preferences.
And I think this would be easy enough to fix (in principle at least, haven't looked at the code).

**Comment by RichardBradley** [comment]
Hi @adriaanm, did you see [my post on scala-internal](https://groups.google.com/forum/#!topic/scala-internals/KQtsxXHDe5Y)? I can't seem to CC on you there as I can't find an email address for you.
What do you think about reopening SI-5365?

**Comment by RichardBradley** [comment]
@Blaisorblade -- Adriaan has re-opened SI-5365 and said that he would accept a PR.

You said "I'd be happy to do the rewrite you suggest if they were ever needed" on scala-internals. Can I take you up on that offer?

Much as I'd love to get a commit into Scala core, realistically I won't have time to look at this for a while and I'm not familiar with the codebase.

**Comment by Blaisorblade** [comment]
> Adriaan has re-opened SI-5365 and said that he would accept a PR.

Well, congratulations on pushing for this :+1: 

> You said "I'd be happy to do the rewrite you suggest if they were ever needed" on scala-internals. Can I take you up on that offer?

Oh, I meant I'd be happy to rewrite my code to fix the warnings, not to fix the compiler :wink: I'd consider doing the fix, but my Scalac-fu is not great, _and_ this week is insanely busy. I'll still try take a look though.

**Comment by RichardBradley** [comment]
OK, thanks anyway. Maybe I will get a chance to commit to `scalac` after all :-)

**Comment by Blaisorblade** [comment]
Hypothesis: assuming guards to be false means just dropping the branch from exhaustiveness checking, so maybe this is conceptually "easy" to implement for somebody knowledgeable. The accidental complexity to do that won't make this trivial, but at least approachable...

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Comment by durban** [comment]
FYI there _was_ a PR for scala/scala with similar contents: scala/scala/pull/4929. (But it wasn't complete, so it wasn't merged, and now it's closed.)

**Comment by milessabin** [comment]
@durban Thanks for the pointer!

Since @retronym has made a start on this it'd be a great candidate for someone to pick up and finish off. Any volunteers?
