### ISSUE TITLE
improve presentation compiler

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#103]
@soc just summarising discussions from the hack day yesterday:
1. timeouts for type inference in the presentation compiler would be amazing. Either throw an exception or just report it as red squiggly warning (e.g. "type inference was taking too long, try a full compile").
2. extending the phases of the presentation compiler to avoid false positives / negatives.

**Comment by fommil** [comment]
related to https://github.com/milessabin/shapeless/issues/458

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
