### ISSUE TITLE
Is it possible to build 'composite' methods, to benefit from JVM's tail call optimisation?

### ISSUE THREAD

**Issue by k0ala** [typelevel/scala#116]
This question/issue was [also posed in the dotty project](https://github.com/lampepfl/dotty/issues/1497), but perhaps it would have a higher priority in the typelevel fork, because of its pure-FP leaning and the potential impact of such a feature on the performance (or even viability) of strongly monadic code. At least, [Kmett ](https://www.reddit.com/r/scala/comments/1tijwv/a_review_by_edward_kmett_of_functional/) and others point to weak TCO as a major impediment to advanced FP in Scala.

The question is, can the compiler replace mutually recursive methods, with a single a self-recursive composite method, in order to benefit from the self-recursive tail call optimization of the JVM? i.e. when the following is detected:

```
def a(...): Result = {
  if (...) new Result(...)
  else b(...)
}

def b(...): Result = {
  if (...) new Result(...)
  else a(...)
}
```

then to replace it with something like this:

```
def ab(..., method: Int): Result = {
   method match {
     case 0 => {  // code from a()
         if (...) new Result(...)
         else ab(..., 1)
     }
     case 1 => {  // code from b()
         if (...) new Result(...)
         else ab(..., 0)
     }
   }
}
```

N.B. I am not familiar with the compiler internals at all, just wondering whether such a thing is possible, as I would love for Scala to have better TCO :smile:

**Comment by dk14** [comment]
I believe JVM itself doesn't have any tail-recursion optimization (in bytecode): http://programmers.stackexchange.com/questions/272061/why-doesnt-java-have-optimization-for-tail-recursion-at-all. Or maybe I just missed something new about Java8 or some specific JVM implementation. Currently scala has to optimize tail recursion by itself (in compile-time).

Talking about self-recursive methods: http://programmers.stackexchange.com/a/157685/158581.
Basically it implies that Java (and Scala as well) doesn't deal with functions only, it deals with methods (which could be overridden in runtime), so in compiler has no way to know which method is actually is going to be called in run-time (yes, it can be hacked by adding run-time checks, but does it worth it?). However, I'd agree that it could be done for objects, but adding such specific case might cost a lot of effort (and, I believe, can affect compiler performance as well), especially when there is relatively simple mechanism that allows developer to resolve that manually (trampolines).

P.S. I think your question belongs to stackoverflow (and it would be easier to discuss it there and give more examples)

**Comment by non** [comment]
@k0ala I think it would be possible to create something like this using a compiler plugin and an annotation (maybe even just a macro and annotation), but it would be a lot of work. To give one example, I think the encoding might look like this:

``` scala
@mutualRec("ab") def addOne(x: Int): Int =
  returnIfZero(x + 1)

@mutualRec("ab") def returnIfZero(x: Int): Int =
  if (x <= 0) x else addOne(x)
```

This would become something like this:

``` scala
def addOne(x: Int): Int = ab(x, 1)
def returnIfZero(x: Int): Int = ab(x, 2)

@tailrec def ab(x: Int, mode: Int): Int =
  if (mode == 1) ab(x + 1, 2)
  else if (mode == 2) if (x <= 0) x else ab(x, 1)
  else sys.error(s"invalid mode: $mode")
```

I started working on something like this several years ago. I didn't hit any technical barrier, but it just ends up being a lot of fiddly work. I'm pretty sure you need both an annotation and a _recursion group_ parameter to that annotation to help delimit methods that should be compiled into the _loop method_ versus those that should run on the stack as normal.

As you can see, this isn't using any fancy JVM technology -- it's just creating a tail-recursive method which _scalac_ can optimize for us into a `while` loop. (We could also compile directly to a while loop ourselves if we wanted.)

**Comment by larsrh** [comment]
This is always possible, but in the general case you need to talk about differing input/output types. This would then potentially introduce overhead by consuming a nested `Either[...]` of all the various possible inputs.

**Comment by non** [comment]
@larsrh As a first pass I would probably constrain the methods to always return the same type, since if you need a disjunction you can explicitly encode that yourself.

**Comment by milessabin** [comment]
This is a great discussion to have, but I don't think it belongs here: this repo and releases made from it are early access to features and fixes which have upstream PR against scala/scala ... so really the discussion belongs there.

**Comment by milessabin** [comment]
@k0ala you should take a look at @wheaties [TwoTails](https://github.com/wheaties/TwoTails) compiler plugin project.

I'm going to close this issue for now. I do think it's valuable to explore these sorts of things directly in the compiler, but seeing as there's activity around a plugin at the moment it makes sense to see how that turns out in practice.
