### ISSUE TITLE
SI2712-regression 

### ISSUE THREAD

**Issue by Baccata** [typelevel/scala#120]
There is a regression with -Ypartial-unification. The symptom appears when trying to resolve an implicit instance of `cats.free.Inject` for a reflexive case (ie, type injected into itself). 

Here is a minimal example : https://github.com/Baccata/si2712-regression-example

**Comment by milessabin** [comment]
This is expected: Cats includes additional instances to work around SI-2712. With this fix enabled these additional instances create ambiguities. I suggest discussing transitional strategies on the Cats gitter channel.
