### ISSUE TITLE
Jekyll artefacts visible in README.md

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#121]
A side-effect of adding support for the microsites plugin is that the default rendering of the README on the github repository landing page has Jekyll-related markup visible at the top:

![screenshot_20161025_085708](https://cloud.githubusercontent.com/assets/131183/19677467/6152ac36-9a91-11e6-9df6-9e21fee7f014.png)

It'd be good to find some way of hiding this.

**Comment by milessabin** [comment]
Paging @juanpedromoreno ...

**Comment by juanpedromoreno** [comment]
@milessabin Yeah, that's because the plugin is copying the README.md file as the microsite documentation. I guess we could create an specific docs folder where we can place the documentation files. Initially, this new folder only would contain an `index.md` file, which would be a copy of the current README.

If that makes sense, I can set it up quickly.

**Comment by milessabin** [comment]
Yes, that makes sense.

Not sure if this is related, but I've just updated the README for 2.11.9 and 2.12.0-RC2. What is the process for having this reflected on http://typelevel.org/scala/? Ask @larsrh to update it manually? What would we need to do to automate this process?

**Comment by larsrh** [comment]
@milessabin The process is automatic; Travis builds and publishes the site on push.

**Comment by larsrh** [comment]
Well, for some reason, the Travis hook has been disabled. I just enabled it again.

**Comment by milessabin** [comment]
Ahh ... interesting. That was me, because it blew up when I pushed to the 2.12.0-RC2-bin-typelevel branch. The problem is that we inherit a .travis.yml from the LBS build, so it's present, so Travis attempts to build and then fails on publishing.

**Comment by larsrh** [comment]
Oh, that's unfortunate. I'd say, remove the upstream `.travis.yml`, then. WDYT?

**Comment by milessabin** [comment]
Yup, that's what I'll do.
