### ISSUE TITLE
Release 2.12.1

### ISSUE THREAD

**Issue by jedesah** [typelevel/scala#126]
It appears as though version 2.12.1 was not released in lockstep with Lightbend Scala.

I am guessing [this part](https://github.com/typelevel/scala#typelevel-scala-2120) of the README should probably be updated as well. Looks like many improvements of the fork were slated for inclusion in Scala Lightbend 2.12.1 but didn't quite make it (but this is just a guess on my part).

**Comment by milessabin** [comment]
I'm not quite done on the work on inductive implicits yet ... very, very close though.

Lightbend Scala releases to release alongside are a very scarce resource, and it's a difficult balance to strike between releasing earlier and using up a release opportunity vs. releasing later and holding people up. 

I very much want the inductive implicits work in 2.11.9, the PR deadline for which is 16/1/2017, and I would make a TLS 2.12.1 release which also includes it as soon as it's done. 2.12.2 is scheduled for 27/2/2017.

Can you wait a little longer?

**Comment by jedesah** [comment]
I can most certainly wait 😄 

Just wanted to bring it to attention in case it had been forgotten, but looks like that's not the case.

**Comment by milessabin** [comment]
Closing in favour of #129.
