### ISSUE TITLE
ValueOf for case classes

### ISSUE THREAD

**Issue by drdozer** [typelevel/scala#127]
At the moment, ValueOf is defined for singleton types, and singleton types themselves are defined very restrictively.

In practice, case classes, like Pair[A, B], have a single inhabitant if and only if 'A' and 'B' have a single inhabitant. The constraint is, I think, that the case class must be final, and that after all type parameters are resolved to actual types, that all fields are themselves singly inhabited. This is trivially true where all fields are of a generic type and these generic types are all instantiated by a singly-inhabited type.

For example:

```scala
    val btc = implicitly[ValueOf["BTC"]]
    val one = implicitly[ValueOf[1]]
    val oneBtc = implicitly[ValueOf[("BTC", 1)]]
```

Clearly, `oneBtc` is singly-inhabited, but there is currently no `ValueOf` instance for it. It's possible to manually derive an instance (thanks @tpolcat):

```
scala> implicit def foo[A: ValueOf, B: ValueOf]: ValueOf[(A, B)] = new ValueOf((valueOf[A], valueOf[B]))
foo: [A, B](implicit evidence$1: ValueOf[A], implicit evidence$2: ValueOf[B])ValueOf[(A, B)]

scala> valueOf[("foo", 42)]
res2: ("foo", 42) = (foo,42)
```

However, this seems like something that the compiler should be dealing with and that it should be verifying has been done sanely.

**Comment by sir-wabbit** [comment]
> In practice, case classes, like Pair[A, B], have a single inhabitant if and only if 'A' and 'B' have a single inhabitant.

Except `null`. It inhabits every non-singleton `A <: AnyRef` type in Scala, including products with singleton type parameters.

**Comment by drdozer** [comment]
I'm not sure how types work at this level - I thought `null` had its own distinct type that already behaved like a singleton type? Leaving aside casting, how could you summon `valueOf[("foo", 42)]` and get `null`?

**Comment by drdozer** [comment]
and why doesn't this invalidate String singletones, as strings are nullable?

**Comment by sir-wabbit** [comment]
I think it's important to make a distinction between `("foo".type, 42.type)` and `("foo", 42).type`. The first is nullable and has two inhabitants: `null` and `("foo", 42)`; the second has only one inhabitant, `("foo", 42) : ("foo", 42).type`.

**Comment by drdozer** [comment]
Understood -- I'd be happy to see that distinction baked in.

**Comment by milessabin** [comment]
> In practice, case classes, like Pair[A, B], have a single inhabitant if and only if 'A' and 'B' have a single inhabitant.

Counterexample,
```scala
case class Foo[T](i: Int)
Foo["foo"](1)
Foo["foo"](2)
```
So you would need to exclude phantom types. But then what about,
```scala
case class Foo[T](l: List[T])
Foo["foo"](Nil)
Foo["foo"](List("foo"))
Foo["foo"](List("foo", "foo"))
```
So you'd need to come up with a criterion which excluded these not-fully-phantom cases as well.

**Comment by drdozer** [comment]
@milessabin  yeah - that's why I was musing "The constraint is, I think, that the case class must be final, and that after all type parameters are resolved to actual types, that all fields are themselves singly inhabited."

**Comment by milessabin** [comment]
Understood. Unfortunately there are counterexamples here too,
```scala
scala> object Foo
defined object Foo

scala> case class Bar[T](t: T)
defined class Bar

scala> Bar[Foo.type](Foo)
res0: Bar[Foo.type] = Bar(Foo$@7fd26ad8)

scala> Bar[Foo.type](Foo)
res1: Bar[Foo.type] = Bar(Foo$@7fd26ad8)

scala> res0 == res1
res2: Boolean = true

scala> res0 eq res1
res3: Boolean = false
```
The standard semantics of `Bar.apply`/`new Bar` would need to be tweaked to accommodate what we want here.

To be clear, I'm not saying that it's impossible, just that the criteria are quite subtle.

**Comment by drdozer** [comment]
ah, so should ValueOf only be defined where there is a single (by eq) inhabiting value, rather than a single equivalence (by ==) value set?

**Comment by non** [comment]
I think that's the safest criteria -- it's hard to guarantee that two objects that are `==` each other will actually behave the same way at runtime.

(Tuples are a case where we can look at the implementation and convince ourselves that it's probably OK. I'm not sure if that class is broad enough to warrant a more general exception.)

**Comment by drdozer** [comment]
Is the operational criteria that ValueOf[T] "behave the same way at runtime" as all possible values of `T`? With appropriate fuzzyness about what it actually means to behave the *same* way, obviously.

**Comment by non** [comment]
I'll defer to @milessabin but the intention of `ValueOf[T]` is to return the single inhabitant of `T` if `T` is a singleton type. A singleton type is one that has only inhabiting value.

If two values can be distinguished, and both are inhabitants of `T`, then `T` is not a singleton type. The strictest possible reading is that if `!(x eq y)` for some `x: T, y: T` then `T` is not a singleton type.

The question is whether we could (and should) choose to relax this constraint at all, and if so, by how much.

I can't imagine relaxing it past *intersubstitutable (barring reflection/eq)* -- any further and it's not clear that the type can usefully be considered a singleton. If `ValueOf[T]` is not guaranteed to behave the same as all existing `x: T` then what do we even mean by it, and how useful could it really be?

**Comment by non** [comment]
By *intersubstitutable* I mean that if `x: T, y: T`, all expressions involving `x` are the same as those where `x` is replaced to `y`. This definition defers the notion of sameness, but certainly includes `==`, side-effects, etc. for any expression involving `T`.

**Comment by drdozer** [comment]
OK, so I agree that anything more relaxed than reflection/eq leads to very likely bouts of insanity.

On the strictest reading currently, I'm not sure that strings can be singletons, as unless they are interned, eq isn't guaranteed to behave as required.

**Comment by non** [comment]
Yes, in the strictest possible reading, you can construct strings that will be equivalent but not `eq` identical.

I don't think this is the usual definition we'd use though. The Scala language/compiler already has a built-in notion of singleton types attached to literal values which does admit singleton types for strings. I may have muddied the waters here (so my apologies).

The SLS [defines](https://www.scala-lang.org/files/archive/spec/2.11/03-types.html#singleton-types) singleton types in terms of paths, so in this case the definition isn't relying on substitutability definitions at all. [Paths](https://www.scala-lang.org/files/archive/spec/2.11/03-types.html#paths) are a generalization of stable identifiers, which can be assumed to point to a single value. That's the sense in which Scala ensures that singleton types correspond to single values (you put `.type` on the end of a path, which you know identifies precisely one value, and now you have a singleton type).

The issue here (I think) is that we can talk about plenty of singleton tuple types (e.g. `(1, "two").type`), but can't use the `[(1, "two")]` syntax to "find" a `ValueOf` instance for them, and that you had worked around this by deriving this instance from weaker evidence (using `ValueOf[A]` and `ValueOf[B]` to construct `ValueOf[(A, B)]`).

**Comment by non** [comment]
I think I do agree that `(3, 4)` is the singleton inhabitant of `(3, 4).type`, so in that sense I agree that I would hope for `implicitly[ValueOf[(3, 4)]]` to succeed. But I think that trying to derive this generically for `(A, B)` in terms of `ValueOf[A]` and `ValueOf[B]` is the wrong approach (as others have pointed out).

For those who are interested, the code that does this is here:

https://github.com/scala/scala/pull/5310/files#diff-7c03397456d3b987549fd039d6b639c6R1330

**Comment by milessabin** [comment]
Singleton types of `String` _literals_ are well defined. Singleton types of `String` references are defined in terms of paths and give rise to much less useful type equalities.

**Comment by milessabin** [comment]
I think we could _make_ `(3, 4)` the single inhabitant of `(3, 4).type`, but that would represent a change to the semantics of the tuple apply/constructor. Eg.

```scala
scala> final val three = 3
three: Int(3) = 3

scala> final val four = 4
four: Int(4) = 4

scala> (three, four)
res0: (Int, Int) = (3,4)

scala> (three, four)
res1: (Int, Int) = (3,4)

scala> res0 eq res1
res2: Boolean = false
```
But maybe this is more than we really need here? You could certainly write something like `ValueOf` for case classes with singleton-typed elements, using shapeless's `Generic`, although clearly the resulting case class values wouldn't be usefully singleton typed themselves.

**Comment by drdozer** [comment]
I may be in danger of solving a 'wrong problem' here. My motivation is lifting value-level computation into types. For example, given a value-level encoding of units (e.g. m/s2 * s ==> m/s), lifting this into singleton types that can then be used to provide unit-safe guarantees on other datatypes. For any suitably interesting problem, the thing you need to lift is a structured type, not just an atomic one.

**Comment by milessabin** [comment]
Can you use type constructors to do that directly more or less as is done in @fthomas's [singleton-ops](https://github.com/fthomas/singleton-ops) library?

**Comment by milessabin** [comment]
Where are we with this?

**Comment by milessabin** [comment]
For the purposes of moving the SIP and implementation forward I'm going to close this in the negative. We can maybe revisit it later.
