### ISSUE TITLE
valueOf[<type alias>] error

### ISSUE THREAD

**Issue by soronpo** [typelevel/scala#128]
TLS is unable to get a singleton value of a singleton type alias.
```
scala> valueOf[1]
valueOf[1]
res0: 1 = 1

scala> type SOne = 1
type SOne = 1
defined type alias SOne

scala> valueOf[SOne]
valueOf[SOne]
<console>:16: error: No singleton value available for SOne.
       valueOf[SOne]
              ^

scala> val one : 1 = 1
val one : 1 = 1
one: 1 = 1

scala> valueOf[one.type]
valueOf[one.type]
res2: one.type = 1

scala> type SOne1 = one.type
type SOne1 = one.type
defined type alias SOne1

scala> valueOf[SOne1]
valueOf[SOne1]
<console>:17: error: No singleton value available for SOne1.
       valueOf[SOne1]
```

**Comment by paulp** [comment]
This is likely the same sort of issue as seen in https://github.com/typelevel/scala/issues/114 - in fact you might want to try the larger patch enclosed there. Bugs of the form "hey, the type alias doesn't work" [go way back](https://github.com/scala/scala/commit/3bf51189f9).

**Comment by milessabin** [comment]
This is fixed in the next TLS release as suggested by @paulp in #114.

**Comment by milessabin** [comment]
Fixed in latest push to https://github.com/scala/scala/pull/5310.

**Comment by paulp** [comment]
Is there some way to see what the change was? Repeatedly force-pushing a single large commit is a pretty unfortunate workflow. I might have thought the PR would at least record the sha of the overwritten commit but I don't see it anywhere.

**Comment by milessabin** [comment]
That's fair comment. I basically fixed and then squashed for the benefit of the ongoing PR against scala/scala.

The fix was your second change [here](https://github.com/typelevel/scala/issues/114#issuecomment-244631566) in full.

**Comment by paulp** [comment]
Ah. Thanks.
