### ISSUE TITLE
Prepare 2.12.1 release

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#129]
PR's to be included,

+ Faster compilation of inductive implicits: https://github.com/scala/scala/pull/5649 (@milessabin)

+ Minimal kind-polymorphism: https://github.com/scala/scala/pull/5538 (@mandubian)

+ Add flags -Ysysdef and -Ypredef to configure root imports: https://github.com/scala/scala/pull/5350 (@andyscott)

+ Infix type printing (SI-4700): https://github.com/scala/scala/pull/5589 (@allisonhb)

+ Trailing commas (SIP-27): https://github.com/scala/scala/pull/5245 (@dwijnand)

+ Literal types (SIP-23): https://github.com/scala/scala/pull/5310 (@milessabin)

+ Exhaustivity of extractors, guards, and unsealed traits (SI-5365): https://github.com/scala/scala/pull/5617 (@sellout)

**Comment by andyscott** [comment]
I'm very much looking forward to this release! So many useful items.

**Comment by milessabin** [comment]
This has now been staged. Please test by adding the following to your builds,

```
scalaOrganization in ThisBuild := "org.typelevel"
scalaVersion in ThisBuild := "2.12.1"
resolvers in ThisBuild += Resolver.sonatypeRepo("orgtypelevel-1198")
```

There might be one final update to @mandubian's the kind polymorphism PR before this is staged.

**Comment by milessabin** [comment]
Staged artefacts built from this branch: https://github.com/milessabin/scala/tree/wip/2.12.1-bin-typelevel.

**Comment by ghost** [comment]
And a big :+1: on the number of contributors with PR's in the release :clap:

**Comment by durban** [comment]
The pattern match exhaustivity improvement (besides being enabled by default) also seems to disallow non-exhaustive catch blocks, _except_ if a type pattern is used:

```scala
scala> case class MyException(x: String) extends Exception
defined class MyException

scala> try { 42 } catch { case MyException(_) => 43 }
<console>:14: warning: match may not be exhaustive.
It would fail on the following input: (x: Throwable forSome x not in MyException)
       try { 42 } catch { case MyException(_) => 43 }
       ^
error: No warnings can be incurred under -Xfatal-warnings.

scala> try { 42 } catch { case _: MyException => 43 }
res3: Int = 42

scala>
```

However, a partial function seems to work fine:
```scala
scala> val pf: PartialFunction[Throwable, Int] = {
     |   case MyException(_) => 67
     | }
pf: PartialFunction[Throwable,Int] = <function1>

scala>
```

CC @sellout

**Comment by sellout** [comment]
@durban Do you have `-Xlint` on in that console by any chance? *fingers crossed*

If so, you’re probably hitting `-Xlint:strict-unsealed-patmat`.

**Comment by sellout** [comment]
But it is surprising to me that `catch` is using a “regular” pattern match rather than the same approach as PartialFunction.

**Comment by sellout** [comment]
@durban So, I’ve only managed to reproduce this locally with `-Xlint`. I will try to make `catch` behave more like the partial-function case, though.

**Comment by durban** [comment]
@sellout Yes, sorry, I do have `-Xlint:_` enabled.

**Comment by durban** [comment]
@sellout However, is it intentional that the behavior is different for `MyException(_)` and `_: MyException`? I think they cover the same cases, still only the first one is detected as non-exhaustive...

**Comment by sellout** [comment]
@durban I think once you do a type pattern, all bets are off, although I don’t know the details of why. Hopefully there is a writeup of that somewhere, because it’s a question that comes up frequently.

**Comment by durban** [comment]
@sellout Type patterns seem to work just fine if matching on a sealed trait (btw this already works in 2.11):

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

sealed trait Foo
final case class Bar(i: Int) extends Foo
final case class Baz(s: String) extends Foo

// Exiting paste mode, now interpreting.

defined trait Foo
defined class Bar
defined class Baz

scala> (Bar(2) : Foo) match {
     |   case _: Bar => 56
     | }
<console>:15: warning: match may not be exhaustive.
It would fail on the following input: Baz(_)
       (Bar(2) : Foo) match {
               ^
res0: Int = 56

scala>
```

With your changes, it also works if the static type is _not_ a sealed trait:

```scala
scala> (Bar(2) : Any) match {
     |   case _: Bar => 56
     | }
<console>:14: warning: match may not be exhaustive.
It would fail on the following input: (x: Any forSome x not in Bar)
       (Bar(2) : Any) match {
               ^
res1: Int = 56

scala>
```

**Comment by milessabin** [comment]
Might be best to move this discussion to: https://github.com/scala/scala/pull/5617.

Unfortunately TLS 2.12.1 was accidentally released (a `sonatypeReleaseAll` SBT release step during a different "org.typelevel" release) so we've missed the boat ... the change will have to go in 2.12.2.
