### ISSUE TITLE
Remove "-Yliteral-types" flag for TLS for Scala 2.13 or even sooner

### ISSUE THREAD

**Issue by soronpo** [typelevel/scala#161]
Literal types have been around for some time now, and there is no evidence of harm when enabled.
I propose removing the flag, which only causes confusion for new users of literal types.

**Comment by milessabin** [comment]
I don't think we should do that until there is a comparable change in Lightbend Scala.

**Comment by milessabin** [comment]
Whoops ... this should have been closed a while back ...
