### ISSUE TITLE
Type arguments on patterns

### ISSUE THREAD

**Issue by kamilkloch** [typelevel/scala#163]
(Probably a shapeless issue, but breaks TLS 4 advertised functionality)

The latest shapeless 2.11/2.12 maven release (2.3.2) does not support type arguments on patterns, as described in https://github.com/typelevel/scala/blob/typelevel-readme/notes/typelevel-4.md#type-arguments-on-patterns-pull5774-paulp

**Comment by milessabin** [comment]
What do you mean by "does not support"?

**Comment by kamilkloch** [comment]
Release 2.3.2 does not contain this change:
https://github.com/milessabin/shapeless/commit/820f12c678a7c1bb2bfb98c201db207cc7fc81de

**Comment by milessabin** [comment]
Gotcha ... that's a shapeless issue, not a TLS issue.
