### ISSUE TITLE
Add an `@uninferrable` annotation

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#17]
I think #14 makes us want to avoid forking scala-library.jar but maybe we can still figure out a way to make this annotation.

**Comment by puffnfresh** [comment]
I think this is more flexible and useful than #16.

**Comment by Blaisorblade** [comment]
> I think this is more flexible and useful than #16.

:+1:

From #16:

> We should be able to add just an annotation without requiring a flag.

But I'd proposing to use it in the std.lib., potentially breaking/revealing bugs in all clients.
Uses only in client software are fine though.

**Comment by propensive** [comment]
Should it be @NonInferrable or @nonInferrable? I prefer the latter because it's more compatible with the sorts of annotations I'm more familiar with, though I agree there's no consistency.

**Comment by non** [comment]
How about `@uninferrable` which dodges the whole question?

**Comment by propensive** [comment]
Well, there's nothing to stop us using `@Uninferrable`... but I like your suggestion. I'm changing the ticket.

**Comment by propensive** [comment]
Ok, I can't do that. But @puffnfresh can.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
