### ISSUE TITLE
Release for 2.12.5

### ISSUE THREAD

**Issue by ghost** [typelevel/scala#180]
Ref https://gitter.im/typelevel/general?at=5ac2cb071130fe3d3695b8e0

**Comment by ghost** [comment]
Ref https://gitter.im/typelevel/scala?at=5accd09e080a38505318e803

Closing, as it looks like 2.12.6 is next 👍

**Comment by SethTisue** [comment]
agree it makes sense for TLS to just wait for 2.12.6.
