### ISSUE TITLE
@reorderable vals as an alternative to lazy vals

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#20]
As @paulp points out, most lazy vals don't need to be double-locked lazy vals because it's only used as a cheap (lazy?) way of guaranteeing safe initialization order, but comes with a performance cost for every subsequent access. In many cases static analysis could avoid this by choosing a safe initialization order at compile time.

`@reorderable` would be used in place of `lazy` for these cases, and the compiler would generate warnings (or errors?) where the dependencies can't be determined statically.

**Comment by odersky** [comment]
Note that we plan to fix this in Don Giovanni the other way round. lazy will mean single-threaded access. You will need to write @volatile lazy if you want to cater to multi-threaded access. The source rewriting tool will rewrite all existing occurrences of lazy to @volatile lazy, unless it can prove that access is single-threaded.

**Comment by ijuma** [comment]
@odersky, is it really wise to make the safe case more verbose (`@volatile lazy`) than the unsafe one (`lazy`)? Particularly given that developers have been trained to expect `lazy val` to be as safe as `val` in the face of concurrent access (lazy vals can cause deadlocks but vals can cause NPEs due to initialisation order).

**Comment by propensive** [comment]
I think changing the default behavior is fine, but it's only justified with a rewriting tool, which doesn't exist yet...

**Comment by ijuma** [comment]
Note that supporting multiple Scala versions will be harder even with the source rewriting tool. Anyway, my main concern is making things less safe for questionable benefit. With Invokedynamic, it's possible to avoid the volatile read after the value is initialised.

Having said that, I like the ideas being discussed in #10.

**Comment by aryairani** [comment]
@odersky +1 for having the safe case be the default, if reusing existing keywords.
A source-rewriting tool is nice; but to @ijuma's point, a brain-rewriting tool is needed here.

We're off-topic though, and @propensive's point is still good.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
