### ISSUE TITLE
for-comprehensions without `_ <- x` and without `yield`

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#21]
This would be cool:

``` scala
for {
  IO.putStrLn("Hello")
  line <- IO.readLine
  IO.putStrLn(line)
} yield ()
```

This would be even cooler:

``` scala
for {
  IO.putStrLn("Hello")
  line <- IO.readLine
  IO.putStrLn(line)
}
```

**Comment by copumpkin** [comment]
:+1:, somewhat unsurprisingly

**Comment by lihaoyi** [comment]
This would also be cool

``` scala
for {
  txt = "Hello"
  IO.putStrLn(txt)
  line <- IO.readLine
  IO.putStrLn(line)
}
```

but +1 for everything that's been suggested here!

**Comment by paulp** [comment]
You can already drop the yield, unless you're doing something with your bucket of units.

**Comment by NightRa** [comment]
Without the yield, it shouldn't necessarily map to unit, it could just do the flatMap's without the final map.

**Comment by milessabin** [comment]
:+1:

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
