### ISSUE TITLE
Update README and put CI in place 

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#22]
It would be great if you updated the README with practical details about this fork and also used a lot of the supporting infrastructure to get a CI up and running. 

We recently did a review of what is out there to assist community dev in https://github.com/ensime/ensime-server so please feel free to take our ideas.

**Comment by Blaisorblade** [comment]
Thanks! I've seen discussions on IRC about CI (but not the details); a problem are build times are too long for Travis.
I've seen people splitting their testsuites, but I suspect that the compiler alone might take far too long to build for Travis, so even this solution might not apply.

**Comment by rorygraves** [comment]
We've recently been having problems with travis as our buid gets bigger/more complex.  It will kill processes that spend too long above single thread.  I suspect that this CI build will suffer from similar issues.

http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

Right now I''m considering setting up a VPS jenkins instance to do main and PR builds (there are plugins to support all of it).

**Comment by aloiscochard** [comment]
Hi Roy,

I did it already with Lars help :
Typelevel-ci.orexio.org

Please see the mailing list for more details

**Comment by rorygraves** [comment]
Awesome.

**Comment by puffnfresh** [comment]
We now have http://typelevel-ci.orexio.org/job/typelevel-scala-pr/ and it's working pretty well. We might have some better stuff coming soon but I'm happy to close this general issue.

I have a PR for a better README. I'll make it better and get it merged.
