### ISSUE TITLE
Binary literals

### ISSUE THREAD

**Issue by aaronlifton3** [typelevel/scala#23]
It would be nice if this scalac fork had built-in non-macro binary literals, similar to the macro-based one found in retronym's macrocosm

E.g. https://github.com/retronym/macrocosm/blob/master/src/main/scala/com/github/retronym/macrocosm/Macrocosm.scala#L72

Example:

``` scala
scala> b"101010"
res4: Int = 42

scala> b"102"
<console>:11: error: exception during macro expansion: invalid binary literal
              b"102"
              ^
```

**Comment by puffnfresh** [comment]
What type would it become? Int? Short? Byte? Long? String?

**Comment by propensive** [comment]
You would want to have some prefix signify the meaning of the subsequent 1s and 0s, and a suffix signify the type, consistent with hex. e.g. `0q1001110100L`. Anything else would be quite inconsistent with what we already have.

**Comment by non** [comment]
I think it could work very similarly to hex literals (`0x111`).

For example:

``` scala
0b111Z // Byte
0b111S // Short
0b111  // Int
0b111L // Long
```

What do you all think?

EDIT: I think this is almost exactly what @propensive is proposing.

**Comment by propensive** [comment]
It's exactly the same, except I was scared of the possible ambiguity of `0b1011` looking like hex. (Obviously it's not -- it's a mental parsing thing, hence my random suggestion of `q`.)

**Comment by Blaisorblade** [comment]
@non's proposal is also coherent [with Java 8's binary literals](http://docs.oracle.com/javase/8/docs/technotes/guides/language/binary-literals.html).
:+1: on using `0b` as a prefix; to consider an alternative, I'd want a mnemonic as good as the one for `b`.

**Comment by som-snytt** [comment]
The `b` mnemonic is weakened by the `b` boolean conversion in format strings.

To counteract that, add `0k` alias for `true` and `0n0` for false.

`0b10` Byte, `0B10` Short, `010` Int, `010L` Long, `0cA` Char.  (No longer fearing the ghost of octal, and no longer wishing to use backslashes for unicode `'\u000A'`. OK, the pun on 0k loosened me up a bit. Pun on bit unintended.)

**Comment by Blaisorblade** [comment]
> The b mnemonic is weakened by the b boolean conversion in format strings.

Valid point.

@propensive wrote:

> Anything else would be quite inconsistent with what we already have.

For instance, this would be inconsistent:

> 0b10 Byte, 0B10 Short, 010 Int, 010L Long, 0cA Char.

However, I realize I had missed some jokes in your message and I'm unsure about others.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
