### ISSUE TITLE
Add @implicitAmbiguous annotation

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#26]
https://issues.scala-lang.org/browse/SI-6806

Should be pretty straightforward.

Motivation:

``` scala
trait =!=[A, B]

implicit def neq[A, B] : A =!= B = null

@implicitAmbiguous("Type is required to not equal ${A}")
implicit def neqAmbig1[A] : A =!= A = null
implicit def neqAmbig2[A] : A =!= A = null
```

**Comment by propensive** [comment]
We should consider how this might interact with #25.

As I see it, it ought to be fine -- it's just the "other reason" why implicit search may fail, and the `@implicitAmbiguous` error messages should be shown in the list too.

Tell me if I'm oversimplifying this.

**Comment by milessabin** [comment]
:+1:

**Comment by puffnfresh** [comment]
We should be able to give a nice error for `any2stringadd` but currently the annotation is not used in the right spot. That should be an easy fix.

**Comment by SethTisue** [comment]
merged in main repo: https://github.com/scala/scala/pull/4673
