### ISSUE TITLE
Singleton types should be inferred wherever there is a bound of <: Singleton

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#27]
This would be a fix for [SI-5103](https://issues.scala-lang.org/browse/SI-5103) which has an incomplete patch by Jason.

**Comment by milessabin** [comment]
See also #15.

**Comment by paulp** [comment]
Like Jason I've tried and failed to implement this. I forget the details.

**Comment by milessabin** [comment]
This is fixed in the SIP-23 PR which will be included in the 2.12.0-RC1 release.

**Comment by SethTisue** [comment]
I thought SIP-23 was targeted for 2.12.1, not 2.12.0-RC1?

**Comment by milessabin** [comment]
This is the Typelevel Scala parallel release which hasn't been announced just yet ... watch this space.

**Comment by SethTisue** [comment]
ah, news to me! ok thx
