### ISSUE TITLE
Introduce a standard scheme for -Z flags based on existing -X and -Y flags

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#31]
Many new features of Typelevel Scala will be "hidden" behind compiler flags, which will behave like the existing -X and -Y flags of mainline Scalac. We need a standard way of defining and implementing these.

**Comment by puffnfresh** [comment]
PR #1 includes a way to list these options:

https://github.com/puffnfresh/scala/commit/d7be78debd97ad429071c20f3f1c3ddf8de2ae21

**Comment by propensive** [comment]
That was, like, three whole days ago... ;)
