### ISSUE TITLE
Scalazzi/Parametric Scala?

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#40]
Would something Scalazzi-like be in scope somehow (behind a flag), with its support for parametricity?

**Comment by milessabin** [comment]
I would say so, yes.

**Comment by puffnfresh** [comment]
I think I managed to get pretty far with this a few months ago. My method was to split `Any` out to have an `AnySynth` subtype, which had `hashCode`, etc.

**Comment by Blaisorblade** [comment]
> I think I managed to get pretty far with this a few months ago.

Cool!

> My method was to split Any out to have an AnySynth subtype, which had hashCode, etc.

Do `AnyRef` and `AnyVal` inherit from that? Or you just mix in `AnySynth` in types which want it?

Finally, for optimizations those methods have different effects. Exposing `eq` and `ne` forbids many optimizations (see #39), while AFAICS all others are not hostile to optimization but just to parametricity. Similarly, `equals` is badly designed, so leaving it out for a typeclass could be interesting.

Should we consider "special" typeclasses instead (whose methods would in fact be intrinsics)? For some source compatibility, methods with the same name could be pimped onto objects — so you'd only have to fix type signatures to get the same results.

**Comment by milessabin** [comment]
Isn't the Scalazzi subset is just that, a subset? So surely we don't need to change any semantics, just reject programs which attempt excluded things?

**Comment by Blaisorblade** [comment]
> Isn't the Scalazzi subset is just that, a subset? So surely we don't need to change any semantics, just reject programs which attempt excluded things?

I've never seen a detailed specification, and I think you're technically right; but you need safe replacements for unsafe tricks to avoid losing expressivity. Those replacements could be available also to standard Scala programs if their interface allows it — if we use typeclasses, that's obviously the case.

For instance, Scalazzi doesn't have Any.equals, but that only makes sense when providing an alternative, like the `Eq` typeclass. That does _not_ violate parametricity. For instance, a value of type `[A]A => A => Bool` must ignore its arguments by parametricity, but `[A: Eq]A => A => Bool` needn't. So, you can write today a useful program using only `Eq` instead of equals (ignoring dependencies), and it would keep compiling if `equals` disappeared from `Any`. So you can program in the intersection of Scalazzi and Typesafe Scala.

If you move `equals` to `AnySynth`, it's less clear to me how to write a program in the common subset — maybe AnySynth should just be an empty trait? It can't be `scala.AnySynth` though — we'd need to modify the Typesafe stdlib.

Similarly, for most `Any` methods you can find some Haskell typeclass allowing similar things: `*InstanceOf` is replaced by "Scrap Your Boilerplate"'s `Data` and `Typeable`.

**Comment by soc** [comment]
+1 to what @Blaisorblade said. I think the typeclass-based approach is the way to go, especially because `AnySynth` would require that each type has only a single implementation of equality, which doesn't make that much sense, while context bounds allow multiple implementations.

**Comment by puffnfresh** [comment]
`AnySynth` was never a proposed solution to equality. It was to get existing, unprincipled code working by just adding a subtype constraint, i.e `A <: AnySynth` rather than `A <: Any`

**Comment by Blaisorblade** [comment]
Good, but is `AnySynth` a good approach for that? Not a rhetoric question.
(I'm sorry to raise so many questions, but I think we're trying to have higher standards of design, comparable to Haskell, with all the consequences this implies).
1. `AnySynth` might be a decent idea, but I'm trying to understand the advantage of enabling the flag and using `AnySynth` where needed. Migration isn't cheap, and most ways to track side effects die on annotation overhead.
   
   I suspect there might be reasons for using any method of `Any`, and there should be a principled way to do that, so that I can convert my code to better code with a clear API. Is `AnySynth` a principled approach, or is it a stop-gap measure? IIUC, it sounds like the 2nd.
   Would enabling/disabling `-Zparametric` (or whatever flag) per file (or even per scope, SIP-18-style) be an easier stop-gap measure?
   
   Anyway, it sounds like we certainly need a principled alternative API.
   `AnySynth` or one of the alternatives might be an additional mechanism if it's good enough. But I fear project ended up replacing (nearly) all uses of `Any` with `AnySynth`, which seems like a loss.
2. I'm worried about everything but equality, where nowadays there is _no_ migration path. Equality is more solved : `Eq` already exists in Scalaz, and I read that @milessabin is working on an alternative to case classes which could generate the needed instances. (That's probably a prerequisite before this is usable: I have implemented and maintained equality by hand in Agda, and trust me, it's not fun).
3. There are benefits to reap from parametric code, and some of the benefits might be negated with `AnySynth` — one example being optimization. I'm still wondering what the answer to this is:
   
   > Do AnyRef and AnyVal inherit from that? Or you just mix in AnySynth in types which want it?
   
   If we end up with `AnySynth` too often, we'd still forbid such optimizations, and maybe other advantages.
4. Whichever version we use, how does code in different dialects interoperate?
5. I suspect we will need a specification with the level of detail of a SIP anyway for this to be good. (I've heard claims that asking for a SIP ends up killing a proposal — that's certainly not my intention.) I also wonder whether this is researchy enough to contribute to it during work time, though that would be too good. (Sorry, PhD student worries).

**Comment by soc** [comment]
@Blaisorblade I think a language import should be enough (instead of AnyValSynth). If developers can't translate their code on a file-to-file base, they have bigger problems to fix than gaining parametricity.

**Comment by non** [comment]
So, I don't have time to thoroughly engage this discussion right now, but I think there are two concerns that are worth separating:
1. Type classes are the right approach for developers to use in general. Part of the benefit of `-Zparametric` is helping developers ensure they are not relying on behavior inherited from `Object`/`Any`.
2. Java/Scala in the wild right now can all be assumed to have `.equals`, `.hashCode`, etc. Even if we choose to ignore it in general we might still want some way of acknowledging this fact in certain cases.

I think that `AnySynth` is a principled acknowledgement of the tension between wanting to use `-Zparametric` globally with the acknowledgement that in Scala every type is a subtype of `Any` that will inherit those methods. By splitting `Any` into `Any` and `AnySynth` we can express two distinct concepts:
- `Any` a totally parametric type parameter of which nothing is known (e.g. `[A]`)
- `AnySynth` the top-level object, with inherited methods like `equals` and `hashCode` (e.g. `[A <: AnySynth]`)

There may be a bolder plan, but this seems like something that is doable and would actually be possible for people to put into practice in a way that's compatible with other Scala that is not compiled under `-Zparametric`.

**Comment by non** [comment]
(That said, introducing a new type under `Any` may be too difficult to pull off technically. I am somewhat biased, as @puffnfresh and I talked through this strategy on IRC months ago and both felt like it was pretty solid. There definitely might be a better way.)

**Comment by aryairani** [comment]
I don't actually know anything about anything, but if trying to maintain compatibility with other compiled code (if!), would it be better to have a new name on top of, or outside of, the existing hierarchy instead of changing the meaning of Any?

**Comment by Blaisorblade** [comment]
Your question isn't stupid, but we want to forbid (in this dialect)
currently allowed but non-parametric code.

The advantage is that if a function has a polymorphic type, with
parametricity you get stronger guarantees on the behavior of this function,
known as "free theorems" (Google for more info). By removing methods from
Any, you get this by default. Otherwise, you'd need to explicitly enable
parametricity.

Since all of this is behind a flag, and since Haskell has shown that
parametricity by default is practical, we shouldn't force programmers to

## annotate each type parameter where they want parametricity.

Paolo Giarrusso

**Comment by aryairani** [comment]
@Blaisorblade Thanks for the explanation — 

I know about Theorems for Free; my question is: is there currently explicit code out there like: 

```
def foo[A<:Any](a: A) = ...
```

and we want `==` and `##` to disappear from that?  

Or could there be, for the purposes of scala/scala interop, a new top of the type hierarchy?  i.e. Instead of renaming old `Any` to `AnySynth`, and new `[A]` to `Any`; leave `Any` as `Any` and make a new supertype above it.

I'm assuming current code doesn't explicitly include Any as an upper bound, e.g.,

```
def foo[A](a: A) = ...
// fully parametric, A does not extend Any
// A extends say, `Top`, which doesn't have any methods, if it must extend something
```

and if you DO want `##` and `==`, you could specify `A <: Any` like above (rather than `A <: AnySynth`).

My question is just about naming and whether it's actually helpful to change the existing meaning of `Any`.

**Comment by puffnfresh** [comment]
@refried this code is out there, in fact, it's in the `Predef`:

``` scala
def identity[A](a: A): A = a
```

This is syntactic sugar for:

``` scala
def identity[A <: Any](a: A): A = a
```

It's actually hard to verify this, since scalac will render types by dropping the `<: Any` part. You'll have to trust me.

Now, we could make it sugar for:

``` scala
def identity[A <: AnySynth](a: A): A = a
```

But that also breaks compatibility.

If we're going to break it, what should we do? I'd prefer not having to remember to include `<: Any` - so I'd prefer it to be the default. I also think it would present itself as the most useful default for Typelevel projects.

Also, I only had some surprisingly successful results from doing the `AnyRef <: AnySynth <: Any` change but I remember it not being a total success. There might be some other avenues would could explore which would be more useful.

**Comment by aryairani** [comment]
@puffnfresh Ok, thanks.  I trust you.

So does the fact that `[A]` is syntactic sugar for `[A<:Any]` show up in jars compiled by scala/scala, or is that a non-issue for cross-compatibility?

```
def parametric[A](a: A) = oldScalaFunction(a) // error?  expected A <: Any, found A
def oldScalaFunction[A /* <: Any */](a: A) = a.## // compiled without parametric flag
```

I get that we want the default upper bound to be the parametric top when the parametric flag is enabled.  Just asking if that parametric top should really be called Any (changing existing semantics; and using AnySynth for the old Any semantics) or called something new.  Eg 

```
AnyRef <: Any <: Top/Universal/Super/etc
```

And if the answer is, "please stop," that's ok too. :-/
(sent very painfully from an iPad)

**Comment by puffnfresh** [comment]
The bytecode does contain the `<: Any` part:

``` java
public static <A extends java/lang/Object> A identity(A);
```

Maybe a better ⊤ type would be more suitable than inserting AnySynth. I think I tried that originally but it didn't work out for some reason. We should try again.

**Comment by aryairani** [comment]
I see, thanks.  And that's `<: AnyRef` even, I guess.  I'm guessing the JVM requires the generics to extend something equal to or subtype of jl.Object, and `<: Any` already involves boxing and magic.  I'm glad there are smarter folks than me working on this :-)

**Comment by paulp** [comment]
FYI <: AnyRef is implied even if it isn't there explicitly - it's a no-op as shown. Yes @refried that's correct about generics being required to be <: Object and Any involving boxing and magic (as well as other things like abstraction leaking and ClassCastExceptions.)

**Comment by soc** [comment]
It probably makes sense to compare notes with what the `any T` people at Oracle are doing.

From my current POV, I'd prefer that they keep all the methods on it, because the only way to "require" the additional methods in Java if they would drop them from `any T` is via upper bounds, which gets really really ugly fast (and I guess we don't want to be cornered into that approach).

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Comment by fommil** [comment]
This is now mostly implemented in https://gitlab.com/fommil/drone-dynamic-agents/blob/master/project/scalafix.conf and I'm planning on creating a dedicated repository so the community can update the rules.
