### ISSUE TITLE
Investigate pathalogical compile-time performance of String singleton types

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#41]
See milessabin/shapeless#50.

**Comment by milessabin** [comment]
Some profiling by @rorygraves suggests that [this](https://github.com/typelevel/scala/blob/2.11.x/src/reflect/scala/reflect/internal/Constants.scala#L219) is probably responsible for a lot of the overhead relative to non-`String` singleton types.

@paulp aside from replacing this with a saner implementation, do you think that making [`ConstantType.safeToString`](https://github.com/typelevel/scala/blob/2.11.x/src/reflect/scala/reflect/internal/Types.scala#L1821) a lazy val would be worth exploring?

**Comment by paulp** [comment]
That method is obscenely expensive if the value class bits aren't working, which apparently they aren't, which is no surprise in the world of CanAllocateFrom. I would forget about trying to memoize the string and fix the basic operations on String. Calling flatMap shouldn't have any allocations except a StringBuilder, like

```
implicit final class OtherStringOps(val s: String) extends AnyVal {
  @inline def flatMap(f: Char => String): String = {
    val sb = new StringBuilder
    var i = 0
    while (i < s.length) {
      sb append f(s charAt i)
      i += 1
    }
    sb.toString
  }
}
```

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
