### ISSUE TITLE
Smarter REPL rendering of infix type constructors in the REPL

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#43]
I've seen a couple of suggestions for how we might decide that a type constructor is intended to be used infix,
- we could assume that all symbolic binary type constructors should be rendered as infix.
- we could add an annotation which specifies a format.

Presumably we would want the constraint that the rendered output is well-formed as a type in Scala source.

**Comment by mpilquist** [comment]
:thumbsup: 

Some previous discussion: https://groups.google.com/d/msg/scala-internals/PqHI0H4r2ZI/He1TSidoS1MJ

**Comment by paulp** [comment]
> Presumably we would want the constraint that the rendered output is well-formed as a type in Scala source.

It's not as if anyone has troubled themselves with that constraint in scala itself, but wouldn't it be nice if A => String => A on the fundamental internal structures wasn't quite such a fuzz tester.

**Comment by adriaanm** [comment]
+1 (on the addition and to some extent on the fuzz shaving)

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Comment by SethTisue** [comment]
+1 to somebody resurrecting this
