### ISSUE TITLE
Better REPL rendering for qualified types

### ISSUE THREAD

**Issue by b-studios** [typelevel/scala#46]
Issue #43 discusses better support for infix type rendering in the REPL. A related but orthogonal issue is that of _qualified types_. On [scala-internals](https://groups.google.com/d/msg/scala-internals/PqHI0H4r2ZI/1Va-_hJmCnAJ) Chris Hodapp made the suggestion to add a "where" clause to the errormessage as in:

``` scala
scala> import shapeless._
import shapeless._

scala> val x = 2 :: 1 :: HNil
x: Int :: Int :: HNil = 2 :: 1 :: HNil

scala> x: String :: String :: HNil
<console>:12: error: type mismatch;
 found   : Int :: Int :: HNil
 required: String :: String :: HNil
 where
  :: is shapeless.::
  HNil is shapeless.HNil
  String is Predef.String
  Int is scala.Int
 x: String :: String :: HNil
 ^
```

Indeed, sometimes I find myself SEDing a complicated error message to the least qualified version. Maybe this could be added as a postprocessing step to the error reporting?

**Comment by mpilquist** [comment]
:thumbsup:

I'd love to see this in both the REPL and in output from the compiler.

**Comment by milessabin** [comment]
Nice idea ... :+1:

**Comment by Blaisorblade** [comment]
I think this is especially important for repeated names. And maybe some names should be dropped by default, like stuff in `Predef` or `scala`.

**Comment by som-snytt** [comment]
FWIW, https://issues.scala-lang.org/browse/SI-8349

**Comment by ceedubs** [comment]
@Blaisorblade if it is reasonable in terms of implementation, I'd rather see the relative type names based on the imports in scope as opposed to special-casing `Predef`, `scala`, etc. Since `Predef` is in scope by default, this should meet the expectations of most people. But by avoiding the special-cases, it could also provide the behavior that would probably be desired by people who are using the `-Yno-predef` or `-Yno-imports` flags.

**Comment by Blaisorblade** [comment]
> @Blaisorblade if it is reasonable in terms of implementation, I'd rather see the relative type names based on the imports in scope as opposed to special-casing Predef, scala, etc. Since Predef is in scope by default, this should meet the expectations of most people. But by avoiding the special-cases, it could also provide the behavior that would probably be desired by people who are using the -Yno-predef or -Yno-imports flags.

That's an interesting point. But whenever I thought of "imports in scope", I fear that the user and compiler might disagree on that, so this might remove too much information (maybe all used imports should be (optionally) mentioned as well?)

For instance:

``` scala
import foo._
import bar._ // Is this foo.bar._ or bar._?
```

I imagine you can get a compiler error because there's shadowing and the user expects the wrong disambiguation.

**Comment by ceedubs** [comment]
@Blaisorblade You raise good points. My comment isn't even an hour old, but I think I may have to backpedal on it already. Often type errors can involve types that aren't imported to the local scope at all, which I wasn't really considering. Furthermore, it is probably a needlessly complicated "solution" to a problem.

However, we will want to be sure that however this is implemented (if it is) avoids any ambiguity if there are multiple types with the same name.

**Comment by Blaisorblade** [comment]
> FWIW, https://issues.scala-lang.org/browse/SI-8349

@som-snytt, I agree this seems highly related, and the implementation could probably share code. Let's inline some notes:

> Instead of printing fully-qualified type names, REPL could optionally print the shortest name allowed by current imports, _possibly respecting renames on import._

http://stackoverflow.com/questions/11066289/suppress-return-types-in-sbt-console-scala-repl

BTW, this reminds me of [sprinter](http://vladimirnik.github.io/sprinter/), which is an actual _pretty_-printer for Scala and already works on the same problem.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
