### ISSUE TITLE
Support for currency symbols in identifiers

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#47]
Scala should allow currency symbols like `£` and `¥` to be used in identifiers. These appear to be excluded only because `$` is treated specially.

**Comment by non** [comment]
Right, especially since (hilariously) `$` is actually legal:

``` scala
scala> val foo$ = 999
foo$: Int = 999

scala> val foo£ = 999
<console>:1: error: illegal character '\u00a3'
       val foo£ = 999
              ^

scala> val bar¥ = 99
<console>:1: error: illegal character '\u00a5'
       val bar¥ = 99
              ^
```

**Comment by paulp** [comment]
Holy conflation of concerns, batman.

**Comment by propensive** [comment]
Motivation: `£` is one of two typable characters on my keyboard (if not yours) which doesn't get any use in Scala...

**Comment by mxswd** [comment]
Can we also support emoji as identifiers?

**Comment by non** [comment]
When you say emoji what do you mean? Almost all of unicode is already supported.

``` scala
scala> val ☹ = false
☹: Boolean = false

scala> val ☺ = true
☺: Boolean = true

scala> def ⚠ = scala.util.Random.nextInt(2) == 0
$u26A0: Boolean

scala> (0 to 5).map(_ => ⚠ == ☹)
res0: scala.collection.immutable.IndexedSeq[Boolean] = Vector(false, true, true, false, true, true)
```

**Comment by puffnfresh** [comment]
:poop: 

```
Hello.scala:2: error: illegal character '\ud83d'
  val 💩 = 1
      ^
Hello.scala:2: error: illegal character '\udca9'
  val 💩 = 1
       ^
Hello.scala:3: error: '=' expected but '}' found.
}
^
three errors found
```

**Comment by non** [comment]
Huh. Does the spec mandate that those characters are illegal?

**Comment by paulp** [comment]
Here's what the spec allows, modulo some ascii. No poo.

```
def p = Set[Int](LOWERCASE_LETTER, TITLECASE_LETTER, OTHER_LETTER, LETTER_NUMBER, MATH_SYMBOL, OTHER_SYMBOL)
val disallowed = 0 until (1 << 16) filterNot (i => p(Character getType i)) toSet

scala> disallowed('\ud83d'.toInt)
res3: Boolean = true

scala> disallowed('\udca9'.toInt)
res4: Boolean = true
```

**Comment by paulp** [comment]
Oh, that's apparently a surrogate. Definitely supplementary characters are out. They barely can be said to work in java let alone scala.

**Comment by som-snytt** [comment]
In my experience, :poop: is punctuation.  But I guess it's an operator, a heavily overloaded symbol of the Other.

```
scala> Character.OTHER_SYMBOL
res4: Byte = 28

scala> Character.getType(0x1f4a9)
res5: Int = 28
```

For currency, it could be called inflation of concerns.

But it would freshen up some tired old sample symbols:

```
scala> val foo$ba££ = 999
foo$ba££: Int = 999

scala> def f[*<*-] = 42     // not sure we've exhausted the emoticon
f: [*<*-]=> Int
```

**Comment by paulp** [comment]
Lots of good stuff in the [general punctuation block](http://www.fileformat.info/info/unicode/block/general_punctuation/images.htm), including the "real" prime symbol ′.

I would use ⁍ all the time. Interrobang‽

**Comment by aryairani** [comment]
I just used the real prime symbol the other day, was very excited when it compiled.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
