### ISSUE TITLE
loosen compatibility requirements

### ISSUE THREAD

**Issue by jdegoes** [typelevel/scala#49]
The current compatibility requirements don't make any sense. If users want to compile their Typesafe / Scala code, they will use the Typesafe compiler. Therefore, the requirement that code compile with the same arguments is onerous and unhelpful, restricting evolution of Typelevel / Scala.

Typelevel / Scala exists for the sole reason of compiling programs that cannot be compiled with Typesafe / Scala, and rejecting some programs that do compile with Typesafe / Scala. 

That fact should be embraced, not tip-toed around.

Therefore, I propose the following compatibility guidelines:
1. If a Scala file contains the import "scala.language.typelevel" (by that name or any other), then the entire file is compiled with Typelevel / Scala. If a Scala file does not contain that import, then the entire file is compiled with Typesafe / Scala (or with a compatibility mode of Typelevel / Scala).
2. Whether compiled by Typelevel / Scala or Typesafe / Scala, the project maintains binary compatibility. That is, programs may freely mix files compiled with both Typelevel / Scala and Typesafe / Scala.

In a Typelevel / Scala file, no unreasonable attempt should be made to preserve source-level or semantic compatibility. The Typelevel / Scala compiler should be allowed to diverge arbitrarily in ways that improve the syntax or semantics of the language.

The expectation should be that users will have to port their project (one file at a time, possibly) to Typelevel / Scala. That said, if there are equally valid ways of solving the same problem, and one of them requires less effort to port code, then that option should generally be preferred.

**Comment by milessabin** [comment]
This has been addressed in detail [here](https://github.com/typelevel/scala/wiki/Typelevel-Scala-Compatibility-Guide) ... see in particular the discussion around `-Z` flags. I also anticipate that we will make use of corresponding language imports.
