### ISSUE TITLE
Type constructor inference

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#52]
I know this is a pie-in-the-sky issue, but what should one do about [type constructor inference](https://issues.scala-lang.org/browse/SI-2712)?

It seems that to have a good story, Scala should either:
- implement higher-order pattern unification
- choose the same restriction as Haskell. [Quoting Paul Chiusano](https://issues.scala-lang.org/browse/SI-2712?focusedCommentId=61270#comment-61270):
  
  > Would it be any easier to just look for partial applications of existing type constructors in left-to-right order? Haskell does roughly this (actually, type constructors are just curried, see below), it is tractable, and people don't seem to have an issue with the limitation, though occasionally you do have to introduce a new type just to flip the order of some type parameters.

**Comment by milessabin** [comment]
I thought I'd already created an issue for this, but no.

I think the Haskell strategy is the way to go, and probably within reach. I think blowing the very practical problem that prompts all the `Unapply` shenanigans up into "Implement higher-order unification" has been largely responsible for the lack of progress on this ... a classic example of the best being the enemy of the good.

**Comment by milessabin** [comment]
This is fixed in Lightbend Scala 2.12 and will be backported to the 2.11.8 Typelevel Scala release.
