### ISSUE TITLE
Add way to get all function signatures

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#53]
Sitting in @markhibberd's Annex talk and he wants "to fix all compilers" - specifically he wants then to be able to output signatures of all functions in some code.

I also do, too, so that I can import the signatures into Hoogle.

**Comment by milessabin** [comment]
I suspect that this is also of interest to @fommil and @rorygraves.

**Comment by rorygraves** [comment]
Yep - that feature would definitely make me happy

**Comment by fommil** [comment]
:+1: https://github.com/fommil/unix/issues/37 I was thinking about doing this but the reality (81 open tickets in ENSIME) means I'll not get round to it. I'd be very happy to see this, although I'm not sure it's necessary for https://github.com/ensime/ensime-server/issues/472

**Comment by propensive** [comment]
@puffnfresh Can you give an example of the sort of output you want, and where it would come from? Would this be a side-effect of compilation?

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
