### ISSUE TITLE
Remove any2stringadd.

### ISSUE THREAD

**Issue by markhibberd** [typelevel/scala#54]
Following on from a related thread Paul has started this here https://github.com/paulp/policy/commit/d5c06772d

How feasible it is to support from behind a flag may be questionable - but this would be a big win if it can be done.

**Comment by ijuma** [comment]
This would be cool indeed.

**Comment by non** [comment]
I had an idea of putting in a `-Z` flag that basically detects these sorts of usages of `+` (and makes them errors). This way new projects could avoid producing this kind of code, but the old projects would still work. Sort of like a built-in wart-remover, but without having to use ambiguous implicits to do it (and presumably with more specific error messages).

What do you think? The other alternative is to do something similar to what Paul did with Policy recently and modify the stdlib/compiler. I don't see a clear way for us to do that without drastically revising our compatibility guarantees.

**Comment by puffnfresh** [comment]
This was some of the motivation for #26 (any2stringadd is just an implicit in Predef) - sadly my PR misses a case and so doesn't give a nice error.

**Comment by paulp** [comment]
@puffnfresh You know the implicit never kicks on expressions like 1 + "bob" because a (String)String method has been synthetically added to Int/Long/etc, yes? See paulp/policy@4bb74b2bb .

**Comment by puffnfresh** [comment]
Also, `-Yno-predef` is already a valid solution to this problem. I think we should also focus on making `-Yno-imports` a sensible thing to use.

**Comment by puffnfresh** [comment]
@paulp I am sadly very aware of that.

**Comment by non** [comment]
Independent of `-Yno-xyz` solutions, we would need something else to disable the methods on `Int` &c. I'll try to prepare a flag-based branch to see how it feels.

**Comment by puffnfresh** [comment]
@non absolutely. That'd be great.

**Comment by puffnfresh** [comment]
I updated #32 to fix the problem with my `implicitAmbiguous` annotation. Now this code:

``` scala
object Nope {
  @annotation.implicitAmbiguous("any2string is disabled")
  implicit def any2stringaddamb1[A](self: A): any2stringadd[A] = ???

  List(1, 2, 3) + "two"
}
```

Gives this:

```
/tmp/Nope.scala:5: error: any2string is disabled
  List(1, 2, 3) + "two"
      ^
```

Which makes me pretty happy.

:cake:

**Comment by propensive** [comment]
Nice! Horrible use case, though... ;)

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Comment by SethTisue** [comment]
related: https://issues.scala-lang.org/browse/SI-194, https://github.com/scala/scala/pull/5235
