### ISSUE TITLE
Support for partial application of types

### ISSUE THREAD

**Issue by EECOLOR** [typelevel/scala#67]
I now have to write this:

``` scala
type CustomEither[A] = Either[Custom, A]
object IdToCustomEither extends (Id ~> CustomEither) {
  ...
}
```

It would be nice to be able to write something like this:

``` scala
object IdToCustomEither extends (Id ~> Either[CustomEither, _])
```

It currently gives the compile error: `takes no type parameters, expected: one`

**Comment by propensive** [comment]
The problem is, how would we distinguish it from this?

```
object IdToCustomEither extends (Id ~> Either[CustomEither, A] forSome { type A })
```

"By its kind" may be a valid answer in this case, but `_` is ambiguous in more general cases.

**Comment by non** [comment]
This issue is related to #6.

As you might see in that discussion, it seems unlikely that we can change `_` to work the way you want in this case.

Currently you could support what you want using [kind-projector](https://github.com/non/kind-projector) and writing:

``` scala
object IdToCustomEither extends (Id ~> Either[Custom, ?])
```

I think this is a totally valid request, but one that might be difficult to achieve.

**Comment by EECOLOR** [comment]
@propensive I probably miss some deeper Scala knowledge. Why do we need to distinguish between those two forms?

**Comment by aryairani** [comment]
What about swapping _ and ? for existentials, like @paulp suggested; with a flag?  Maybe the question belongs at #6...

**Comment by propensive** [comment]
@EECOLOR These are two different types, with different kinds. `Either[String, _]`
is the same as `Either[String, T] forSome { type T }` which is a "proper type", as it can have values like `Left("Hello world")` and `Right(42)`.

However, the partially applied type, a type constructor, which you can think of as a function from one proper type to another proper type, is not itself a proper type, and (as such) can have no values. In Scala we currently have to write it as `({ type λ[T] = Either[String, T] })#λ`, but it would be nice to have a more lightweight syntax like `Either[String, ?]`.

**Comment by EECOLOR** [comment]
@propensive In my mind the compiler can easily distinguish between what you call "proper types" and "type constructors".

The only situation where you need to write a type lambda, is if the expected type is a type constructor. The natural transformation example is one where it's very clear:

```
type ~>[F[_], G[_]]
```

The compiler detects these types of constructions as it requires us to enable higher kinded types. 

In what situations would `Either[String, _]` become ambiguous?

``` scala
// _ means can take anything
val x:Either[String, _]

// Partially apply Either so it becomes a type constructor with a single type argument
implicitly[Functor[Either[String, _]]]
```

What situation am I overlooking?

**Comment by propensive** [comment]
@EECOLOR That's the crux of it... Have a look at this chat on the Typelevel mailing list, which I started as a result of these discussions here...

https://groups.google.com/d/topic/typelevel/dIyV5e-C7SI/discussion

**Comment by EECOLOR** [comment]
Wow... So if I understand correctly, it's possible, but tricky to get right.

It also seems a subject that will drag a lot of other stuff into the conversation.

So I guess we need to wait till a smart person comes along with enough compiler knowledge capable of adding it.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
