### ISSUE TITLE
Add annotation to specify operators precedence.

### ISSUE THREAD

**Issue by 4lex1v** [typelevel/scala#69]
Is it possible to add some kind of annotation to control the precedence of functions with symbolic names, something similar to what Haskell has? 

``` scala
implicit class ArrowAssoc[A](left: A) {
  @infixr(6) def ->[B](right: B): (A, B) = (left, right)
}
```

So the code like this: `"string" -> "value" -> 10`, would be parsed as `("string" -> ("value" -> 10))`.

**Comment by paulp** [comment]
This would be a lifesaver for writing code and a potential anchor for reading it. If you attach the lifesaver to the anchor, does it sink or float? I think it floats in general but maybe not in scala.

**Comment by julien-truffaut** [comment]
+1 would be extremely useful. 

@paulp I don't think the use of a static table (as it is now) makes the code more readable. AFAIK, most people don't know what is the current operators precedence.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Comment by soronpo** [comment]
FYI
https://contributors.scala-lang.org/t/sip-nn-make-infix-type-alias-precedence-like-expression-operator-precedence/471
