### ISSUE TITLE
Move unicode-escaping post-parser

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#7]
> Unicode escaping currently happens before the parser, making it intractable. Unicode parsing should be handled in non-raw String literals. This would allow, for example, LaTeX commands such as "\usepackage" to be embedded within raw string literals without deliberate obfuscation.

**Comment by Blaisorblade** [comment]
:+1:

**Comment by soc** [comment]
https://issues.scala-lang.org/browse/SI-3220 is related.

**Comment by non** [comment]
@soc Right, that ticket was definitely an inspiration. In my mind I wanted to do the "right" thing (from my POV) which is to remove the feature except in the cases where it is definitely needed (string and character literals).

Almost all technology is now Unicode/UTF-8 aware, and beyond that the Scala community seems to have agreed on providing alternatives to any uses of unicode in public APIs. Thus I would say that the feature (which is inherited from Java) is not worth it for us.

If there are folks who heavily rely on this feature I'd be interested to hear counter-arguments. So far everyone I've talked to has been very supportive of this change.

(EDIT: And of course, we may decide on source compatibility guidelines which are too strict to allow us to remove unicode escapes entirely. In that case, I would support a more limited hack like the one @soc proposed in the linked ticket.)
