### ISSUE TITLE
Make sensible language flags become no-ops

### ISSUE THREAD

**Issue by puffnfresh** [typelevel/scala#72]
Let's make these the default imported features:
- higherKinds
- implicitConversions
- existentials

But maybe not the last one.

**Comment by tonymorris** [comment]
:+1:

**Comment by milessabin** [comment]
Agreed ... including the question mark over existentials.

**Comment by propensive** [comment]
I'm not so eager to do this. It seems like we might be just swapping some implicit imports for some -Z flags, which are a less flexible solution (no scoping control; more command-line configuration).

**Comment by propensive** [comment]
But go ahead and convince me.

**Comment by puffnfresh** [comment]
@propensive there's no need for a -Z flag. This is making flags do less so that people have a better time working in Scala.

**Comment by propensive** [comment]
@puffnfresh I was wondering about that. Do we not introduce potentially ambiguous implicits when compiling TSS code which already defines implicits for these things?

**Comment by puffnfresh** [comment]
@propensive implicits shouldn't be introduced, implicits should just not be used for these things.

**Comment by propensive** [comment]
@puffnfresh Oh, fine. Ok! :)

**Comment by puffnfresh** [comment]
Closed via #74.
