### ISSUE TITLE
better jdkHome resolution

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#75]
PR coming at some point when I have time to do it... we use this logic in ensime-server to detect the JDK home. The current Properties.jdkHome logic is not great

``` scala
  // WORKAROUND: https://github.com/typelevel/scala/issues/75
  val jdkDir: File = List(
    // manual
    sys.env.get("JDK_HOME"),
    sys.env.get("JAVA_HOME"),
    // osx
    Try("/usr/libexec/java_home".!!.trim).toOption,
    // fallback
    sys.props.get("java.home").map(new File(_).getParent),
    sys.props.get("java.home")
  ).flatten.filter { n =>
      new File(n + "/lib/tools.jar").exists
    }.headOption.map(new File(_)).getOrElse(
      throw new FileNotFoundException(
        """Could not automatically find the JDK/lib/tools.jar.
      |You must explicitly set JDK_HOME or JAVA_HOME.""".stripMargin
      )
    )
```

**Comment by som-snytt** [comment]
For comparison,

https://github.com/scala/scala/blob/v2.11.2/src/compiler/scala/tools/util/PathResolver.scala#L142

**Comment by fommil** [comment]
@som-snytt that's interesting. ~~They don't check the "parent of the java.home" directory, which is the canonical place to look.~~ they seem to do the right thing, but the `jdkHome` resolution does not.

**Comment by SethTisue** [comment]
for the record, this doesn't work with Java 6 on Mac OS X. (`lib/tools.jar` isn't present.) Java 7 and 8 are fine.

**Comment by som-snytt** [comment]
My mother has Java 6 on her old Snow Leopard. She's eighty something.

FTR, Java 9 neither. Or did you mean 9? Sometimes during cards I have to count the spots to tell them apart.

**Comment by ninjasoul** [comment]
Looks like it's not working for Windows paths also. I have my JAVA_HOME set to `C:\Software\JDK`. Doesn't translate over to UNIX style paths.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
