### ISSUE TITLE
language support for case classes a la carte

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#79]
It would be incredibly useful to have language support for @milessabin's case classes a la carte

https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/alacarte.scala

e.g. perhaps as a type parameter on the `case` keyword, to generate the boilerplate

``` scala
case[DefaultCaseClassDefns] class Foo(val i: Int, val s: String)
```

to generate - from https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/alacarte.scala - the boilerplate

``` scala
   object FooDefns extends DefaultCaseClassDefns {
    type C = Foo
    val ops = Ops
  }

  object Foo extends FooDefns.CaseClassCompanion
  class Foo(val i: Int, val s: String) extends FooDefns.CaseClass
```

(I'm not entirely sure what we do about the `val`s, it would be nice to lose them also if the `Defns` extends from some magical `ExposeFields` trait or something similar)

**Comment by xeno-by** [comment]
What about having macro annotations do this? Something like `@case[...] class ...`?

Also, just wondering, what are the performance implications of the current implementation of case classes a la carte?

**Comment by aloiscochard** [comment]
I think support for "case classes a la carte" only is quite restrictive.

If feel to me that it should be possible to have a mechanism that could be more general and used as well to have, for example lens support at language level.

**Comment by xeno-by** [comment]
Well, as long as we have macro annotations, we can do a lot of interesting stuff in a general way, supporting things like w/e a la carte, lenses, type providers, etc.

**Comment by aloiscochard** [comment]
@xeno-by what are the advantages of using macro vs a more ad-hoc approach?

An obvious disadvantage to me is syntax.

**Comment by xeno-by** [comment]
With macros, nothing has to be hardcoded into the compiler. E.g. if someone doesn't quite like the provided facility, they can just unimport it and import their stuff. Also, if there's a bug in the case class functionality, it can be fixed independently of the compiler's release cycle (I think that's important even for really agile forks).

Sometimes localized codegen provided by macros isn't enough, but that's not one of those cases, so I think macro annotations are a good fit.

UI can be tuned, of course. One option would be to say that `case class ...` desugars into `@case class ...`. We could also discuss other possibilities.

**Comment by aloiscochard** [comment]
@xeno-by beside the potential desugaring of `case class` to `@case class`, it seems to me that everything you propose (I mean the way to do it...) should rather be implemented as a library using scala-meta rather than in a forked compiler.

What are the advantage then of using macro inside a forked compiler instead of writing them as a library and only having potential sugar magic in the forked compiler code?

**Comment by xeno-by** [comment]
Yes, that's exactly what I had in mind. If something is hardcoded in the compiler, it's there to stay. If it's a macro, then it can and should be in a library.

**Comment by fommil** [comment]
A plugin would be idea, I've created the above ticket on Scalaxy. Closing here as the case (ho ho) for keeping it out of the compiler is strong.

Now, should `case` itself be removed and replaced with a plugin :smile:
