### ISSUE TITLE
Coercible for Scala for "Safe Zero-cost Coercions"

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#81]
Is there hope of having [Safe Zero-cost Coercions for Haskell](http://www.seas.upenn.edu/~sweirich/papers/coercible.pdf) in Scala? This would be convenient.

Maybe Scalaz's `Tag.subst` is fine, but right now I'm not convinced:
https://github.com/scalaz/scalaz/commit/d90a5b568588e44acd35a9d6ae0a4a1baae1aaeb#commitcomment-8301591

Background/motivation: If you want your modules to be picked implicitly (through typeclasses) rather than explicitly (through ML modules), many people argue you should have coherence to avoid ever picking the  wrong typeclass dictionary. To keep coherence when multiple instances make sense/when you want modularity, you need newtypes.

**Comment by Blaisorblade** [comment]
See also scalaz/scalaz#838.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
