### ISSUE TITLE
Redesign PartialFunction

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#82]
I used to think that `PartialFunction` corresponds to a partial function with an extra method for testing its domain. I've tried to actually match that to the documentation, and realized I was mistaken as discussed in scala/scala#4074.

The only thing belonging in the standard library to some extent (as an implementation concept) is`NonExhaustivePatternMatch` (described [here](https://github.com/scala/scala/pull/4074#issuecomment-60832570)). I don't know what's scalaz's stance on `PartialFunction`/`A => Option[B]`/`A => LazyOption[B]`, or whether `PartialFunction` is safe enough after you forbid exceptions.

**Comment by Blaisorblade** [comment]
The conclusion was inspired by this tweet of Paul:

> [It is the gravest of fallacies to imagine anyone can document their way out of unnecessary complexity.](https://twitter.com/extempore2/status/523871835616579584)

On compatibility: I'm aware of the compatibility problems, and I hope this can be addressed somehow with some clever deprecations/compatibility scheme.

**Comment by soc** [comment]
One reason I always avoided PartialFunctions is the butt-ugly syntax. Work on PartialFunction could take that into account, as well as things like `=?>` which are nice but have the wrong associativity currently.

**Comment by Blaisorblade** [comment]
#### On associativity of `=?>`

I use a right-associative variant, IIRC `=?>:`. The only alternative I can think of is making _type_ operators ending in `>` and starting with `=` right-associative, but I don't like adding an extra corner case to the current rules (even assuming this is compatible with existing code).

Haskell-style infix declarations might be better, but they fit less with the current Scala design: I don't like a language that combines inferred associativity and precedence with user-specified ones, that sounds to me like a typical "design by committee" problem since I find the second idea superior. Also, with infix declarations, anybody who knows the current rules would stop being just able to read code.

If there's any interest in changing precedence rules, let's split a separate issue out of here.

**Comment by Blaisorblade** [comment]
> One reason I always avoided PartialFunctions is the butt-ugly syntax.

I'm focusing myself on the semantics, but I'm listening. What would you replace `{ case x: String => ... }` with, if that's what you mean?

**Comment by soc** [comment]
Here are some ideas: https://groups.google.com/d/msg/scala-internals/hY4A3PVmd_o/bBKgj0tIYMkJ

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
