### ISSUE TITLE
Allow explicit type parameters in patterns to drive generic extractors

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#85]
We cannot currently write patterns like this:

```
myString match {
  case As[Int](i) => i
  case As[Char](c) => c.toInt
}
```

because even if we were to define an extractor like this

```
object As {
  def unapply[T: FromString](s: String): Option[T] = implicitly[FromString[T]].from(s)
}
```

type parameters in patterns do not parse, so can't get passed from the case clauses to the unapply method of the extractor. But they could be.

**Comment by gourlaysama** [comment]
:+1:!

This one goes all the way back to the dark times of three-digit issues: [SI-884](https://issues.scala-lang.org/browse/SI-884).

**Comment by Blaisorblade** [comment]
:+1: !

Is this just about extending the parser, or is there more to it? Let me be naive and assume the fix must be more complex, otherwise why has this languished for so long? (Yes, I know, I'm being naive). I remember the AST representation was damn confusing.

**Comment by gourlaysama** [comment]
Actually it"s the other way around: the parser part has been "implemented" since 2.9 (51e4a6a), but there needs to be support for this in the typer and probably patmat.

Before 2.9:

``` scala
<console>:2: error: '=>' expected but '[' found.
         case isClass[String] => "foo"
```

After 2.9:

``` scala
<console>:9: error: not found: type isClass
         case isClass[String] => "foo"
```

**Comment by paulp** [comment]
Good luck guys. You're going to need it.

**Comment by Blaisorblade** [comment]
Just to be more specific, the last time I ran away from pattern matching code led to this explanation:

https://groups.google.com/d/msg/scala-internals/KWgkE03w038/jq2bETxbt-4J

In Jason's words, "pattern typing does follow a twisty path".

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
