### ISSUE TITLE
A warning should be issued when defining an implicit def with multiple non-implicit parameters

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#89]
These serve very little purpose, unless code is somewhere requesting a `Function2[X, Y, Z]`, which doesn't seem like a great idea. The user probably intended to make the parameters implicit.

**Comment by milessabin** [comment]
I don't think it's unreasonable to define and request an implicit value of some non-unary function type. It's maybe not that common, but I don't think that's enough of a reason to complain.

**Comment by propensive** [comment]
Ok, I'll close this if nobody else has been burned (I wasted, oh, a good 20 seconds...) by this.

**Comment by SethTisue** [comment]
perhaps should be an Abide rule?

**Comment by milessabin** [comment]
I think nearly two years is long enough to wait for someone to speak up for this ;-) Closing ...
