### ISSUE TITLE
Explore desugaring `while` in for-comprehensions to `takeWhile`

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#90]
As discussed here:

https://groups.google.com/d/topic/scala-language/M_9FjqbAhhU/discussion

and less recently here:

http://scala-programming-language.1934581.n4.nabble.com/For-comprehensions-and-breaks-td1991725.html#a1991797

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
