### ISSUE TITLE
Stream's implementations of methods are more general/efficient than TraversableLike

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#94]
As discussed in https://groups.google.com/d/msg/scala-internals/zf36JWUoSAg/txmX3ZoAF9UJ it would appear that Stream implements a lot of methods more efficiently than TraversableLike because it uses `@tailrec` instead of `while()`... and I mean efficient in all circumstances because the only difference at the bytecode level is dropping a reference to the head and therefore allowing GCs to potentially incrementally collect.

It would be good to therefore move the relevant implementations from Stream into TraversableLike, and rethink some of the other collection methods as `@tailrec`.

**Comment by milessabin** [comment]
IIRC the reason for _not_ doing that is that methods on `TraversableLike` are supposed to be non-final to allow overriding in subtypes. And non-final methods can't be `@tailrec`.

Nb. I'm not saying I approve of this situation, but I don't think that just promoting the sensible definition from `Stream` to `TraversableLike` is going to fly.

The alternative is to duplicate the sensible definition in `List` etc. etc. at which point @paulp pops up with a wagging finger and a (justifiably) snarky comment.

**Comment by fommil** [comment]
argh, you're right. Perhaps the `final @tailrec` implementations should go in a separate trait that is then mixed in by everything that doesn't override.

**Comment by fommil** [comment]
actually, it really is only `List` that would benefit from this type of implementation. So perhaps all the common Stream/List functionality should be in a separate trait.

**Comment by paulp** [comment]
> So perhaps all the common Stream/List functionality should be in a separate trait.

We could call it, oh I don't know, LinearSeq.

Of course, how could it be so simple. https://issues.scala-lang.org/browse/SI-8754

**Comment by fommil** [comment]
That's the monkey.

**Comment by paulp** [comment]
Looking back at that ticket, it's hysterical that you're supposed to implement a linear sequence without any linear sequence methods. This works out about as well as you'd expect.

```
scala> new scala.collection.immutable.LinearSeq[Int] { def apply(x: Int): Int = x ; def length = 1 }
java.lang.StackOverflowError
  at scala.collection.SeqLike$class.lengthCompare(SeqLike.scala:87)
  at $anon$1.lengthCompare(<console>:8)
  at scala.collection.SeqLike$class.isEmpty(SeqLike.scala:100)
  at $anon$1.isEmpty(<console>:8)
```

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
