### ISSUE TITLE
incorrect usage instructions?

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#96]
the instructions say to do this

``` scala
scalaVersion := "2.11.3-typelevel"
libraryDependencies += "org.scala-lang" % "scala-typelevel" % scalaVersion.value
resolvers += Resolver.mavenLocal
```

now, versions aside (I believe `2.11.5-typelevel` is what is currently built), I don't believe that the `libraryDependencies` line is needed. Or is this an extra package that is only present in typelevel?

However, users might need to add the following (and probably for other artefacts published by the base scala lang project)

``` scala
libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-compiler" % scalaVersion.value force(),
  "org.scala-lang" % "scala-reflect" % scalaVersion.value force(),
  "org.scala-lang" % "scalap" % scalaVersion.value force()
)
```

as we do in https://github.com/ensime/ensime-emacs/pull/131

**Comment by milessabin** [comment]
This is about to be obsoleted by the Typelevel Scala reboot. Closing.
