### ISSUE TITLE
(Optionally) inferring singleton type annotations for values with dependent type members

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#99]
When inferring `a`'s type in `val a = stableValueName`, Scalac historically widens `stableValueName.type` to the underlying non-singleton type. That's often unproblematic in practice (though it looks rather ad-hoc), but it can be annoying when using types that are members of `stableValueName`, forcing to write `val a: stableValueName.type = stableValueName` when using nested cakes.

I just realized that (under some option, for compatibility) one could detect whether `stableValueName` contains member types and disable widening.

I still suspect that never widening might be a more consistent behavior. This gives less information hiding by default, but arguably information hiding should be a conscious act.

**Comment by milessabin** [comment]
The compiler will infer the singleton type if the val is effectively final. Please reopen as an issue against scala/scala if that doesn't cover the scenarios you have in mind.
